# Generated by Django 4.1.7 on 2023-02-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-published',)},
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
