# Generated by Django 4.1.7 on 2023-03-01 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_blog_authors_blog_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
