# Generated by Django 4.1.7 on 2023-03-14 06:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_options_rename_publisher_blog_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(default='contenido por defecto'),
            preserve_default=False,
        ),
    ]
