# Generated by Django 4.1.7 on 2023-03-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='birthday',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(default=5043829, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
